server:
  tomcat:
    max-connections: 10
    accept-count: 2
    threads:
      max: 10
      min-spare: 10

spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  output:
    ansi:
      enabled: always

logging.level:
  org.hibernate:
    SQL: debug
    orm.jdbc.bind: trace
  com.example.springplayground: trace