
spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  output:
    ansi:
      enabled: always